dev-capec/force-app/main/default/objects/Entrada__c/Entrada__c.object-meta.xml
<CustomObject>
    <label>Entrada</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Entrada</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entradas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dev-capec/force-app/main/default/objects/Entrada__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Entradas</relationshipLabel>
    <relationshipName>Entradas</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/objects/Entrada__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dev-capec/force-app/main/default/classes/EntradasTriggerHandler.cls
public without sharing class EntradasTriggerHandler 
{

    public static void handleBeforeInsert(List<Entrada__c> records)
    {
        List<PricebookEntry> pbEntries = PricebookEntriesSelector.selectByProduto(Utils.getSetIds(records, Entrada__c.Produto__c));

        for (Entrada__c record : records)
        {
            if (record.Valor__c == null)
            {
                handleValorPadrao(record, pbEntries);
            }            
        }
    }

    private static void handleValorPadrao(Entrada__c record, List<PricebookEntry> pbEntries)
    {
        for (PricebookEntry pbEntry : pbEntries)
        {
            if (record.Produto__c.equals(pbEntry.Product2Id))
            {
                record.Valor__c = pbEntry.UnitPrice;
                break;
            }
        }

        if (record.Valor__c == null)
        {
            record.Valor__c.addError('Preencha esse campo.');
        }
    }
}