dev-capec/force-app/main/default/objects/ItemEstoque__c/ItemEstoque__c.object-meta.xml
<CustomObject>
    <label>Item de Estoque</label>
    <nameField>
        <displayFormat>IE-{000000}</displayFormat>
        <label>Item de Estoque</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de Estoques</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dev-capec/force-app/main/default/objects/ItemEstoque__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens de Estoques</relationshipLabel>
    <relationshipName>ItensEstoques</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/classes/ItensEstoquesSelector.cls
public without sharing class ItensEstoquesSelector 
{
    private static ItensEstoquesSelector instance = null;
    public List<ItemEstoque__c> itens {get; private set;}

    private ItensEstoquesSelector(){}

    public static ItensEstoquesSelector getInstance()
    {
        if (instance == null)
        {
            instance = new ItensEstoquesSelector();
        }

        return instance;
    }

    public List<ItemEstoque__c> selectByProduto(Set<Id> ids)
    {
        if (itens == null)
        {
            itens = [
                SELECT Id, Produto__c, Quantidade__c
                FROM ItemEstoque__c
                WHERE Produto__c IN :ids
            ];
        }

        return itens;
    }
}