dev-capec/force-app/main/default/objects/ItemDoacao__c/ItemDoacao__c.object-meta.xml
<CustomObject>
    <label>Item de Doação</label>
    <nameField>
        <displayFormat>ID-{000000}</displayFormat>
        <label>Item de Doação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de Doações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dev-capec/force-app/main/default/objects/ItemDoacao__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens de Doações</relationshipLabel>
    <relationshipName>ItensDoacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemDoacao__c/fields/ProdutoRecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>ProdutoRecordTypeId__c</fullName>
    <formula>Produto__r.RecordType.Id</formula>
    <label>ProdutoRecordTypeId</label>
    <type>Text</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemDoacao__c/recordTypes/CestaBasica.recordType-meta.xml
<RecordType>
    <fullName>CestaBasica</fullName>
    <active>true</active>
    <label>Cesta básica</label>
</RecordType>

dev-capec/force-app/main/default/classes/ItensDoacoesTriggerHandler.cls
public without sharing class ItensDoacoesTriggerHandler
{    
    public static void handleAfterInsert(List<ItemDoacao__c> records)
    {
        Map<Id, ItemDoacao__c> cestaBasicaItemDoacao = new Map<Id, ItemDoacao__c>();

        for (ItemDoacao__c record : records)
        {
            if (record.ProdutoRecordTypeId__c.equals(Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CestaBasica').getRecordTypeId()))            
            {
                cestaBasicaItemDoacao.put(record.Produto__c, record);
            }
        }

        handleAfterInsertCestasBasicas(cestaBasicaItemDoacao);
    }

    public static void handleAfterInsertCestasBasicas(Map<Id, ItemDoacao__c> cestaBasicaItemDoacao)
    {
        if (!cestaBasicaItemDoacao.isEmpty())
        {
            insert ItensDoacoes.newInstance(cestaBasicaItemDoacao.values()).createByCestaBasica(cestaBasicaItemDoacao.keySet());
        }

        delete cestaBasicaItemDoacao.values();
    }
}