dev-capec/force-app/main/default/objects/ItemCestaBasica__c/ItemCestaBasica__c.object-meta.xml
<CustomObject>
    <label>Item da Cesta Básica</label>
    <nameField>
        <displayFormat>ICB-{000000}</displayFormat>
        <label>Item da Cesta Básica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens das Cestas Básicas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dev-capec/force-app/main/default/objects/ItemCestaBasica__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Padrão</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens</relationshipLabel>
    <relationshipName>Itens</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemCestaBasica__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens das Cestas Básicas</relationshipLabel>
    <relationshipName>Itens</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemDoacao__c/ItemDoacao__c.object-meta.xml
<CustomObject>
    <label>Item de Doação</label>
    <nameField>
        <displayFormat>ID-{000000}</displayFormat>
        <label>Item de Doação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de Doações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dev-capec/force-app/main/default/objects/ItemDoacao__c/fields/ItemCestaBasica__c.field-meta.xml
<CustomField>
    <fullName>ItemCestaBasica__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Item da Cesta Básica</label>
    <type>Checkbox</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemDoacao__c/fields/ItemEstoque__c.field-meta.xml
<CustomField>
    <fullName>ItemEstoque__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item de Estoque</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>O estoque desse item está zerado.</errorMessage>
        <filterItems>
            <field>ItemEstoque__c.Quantidade__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ItemEstoque__c</referenceTo>
    <relationshipLabel>Itens de Doações</relationshipLabel>
    <relationshipName>ItensDoacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemDoacao__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens de Doações</relationshipLabel>
    <relationshipName>ItensDoacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemDoacao__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemEstoque__c/ItemEstoque__c.object-meta.xml
<CustomObject>
    <label>Item de Estoque</label>
    <nameField>
        <displayFormat>IE-{000000}</displayFormat>
        <label>Item de Estoque</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de Estoques</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dev-capec/force-app/main/default/objects/ItemEstoque__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens de Estoques</relationshipLabel>
    <relationshipName>ItensEstoques</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/classes/ItensEstoques.cls
public without sharing class ItensEstoques implements IItensEstoques
{
    public List<ItemEstoque__c> records;

    public ItensEstoques(List<ItemEstoque__c> records) 
    {
        this.records = records;
    }

    public static ItensEstoques newInstance(List<ItemEstoque__c> records)
    {
        return new ItensEstoques(records);
    }

    public void devolveQuantidade(List<ItemDoacao__c> itens)
    {
        for (ItemDoacao__c itemDoacao : itens)
        {
            Integer i = 0;
            ItemEstoque__c item;
            do
            {
                item = records.get(i);
                i++;
            } while (i < records.size() && !item.Produto__c.equals(itemDoacao.Produto__c));

            if (item.Produto__c.equals(itemDoacao.Produto__c))
            {
                item.Quantidade__c += itemDoacao.Quantidade__c;
            }
        }
    }

    public void handleDoacoes(List<ItemDoacao__c> itensDoacoes)
    {
        for (ItemDoacao__c itemDoacao : itensDoacoes)
        {
            System.debug('item doacao: ' + itemDoacao);
            Decimal totalDoacao = itemDoacao.Quantidade__c;
            for (ItemEstoque__c itemEstoque : records)
            {
                System.debug('item estqoue avaliado: ' + itemEstoque);
                if (itemDoacao.Produto__c.equals(itemEstoque.Produto__c))
                {
                    System.debug('item de estoque deu match com item de doação');
                    System.debug('totaldoacao: ' + totalDoacao);
                    if (totalDoacao == 0)
                    {
                        break;
                    }
                    else
                    {
                        System.debug('qtd em estoque: ' + itemEstoque.Quantidade__c);
                        if (totalDoacao <= itemEstoque.Quantidade__c)
                        {
                            itemEstoque.Quantidade__c -= totalDoacao;
                            totalDoacao = 0;
                            break;
                        }
                        else
                        {
                            totalDoacao -= itemEstoque.Quantidade__c;
                            itemEstoque.Quantidade__c = 0;                        
                        }  
                        
                        system.debug('total doacao foi pra: ' + totalDoacao);
                    }
                }
                
            }

            if (totalDoacao > 0)
            {
                itemDoacao.Quantidade__c.addError('Quantidade solicitada (' + itemDoacao.Quantidade__c + ') indisponível em estoque.');
            }
        }

        update records;
    }

    public void handleQtdEstoque(ItemDoacao__c item, Decimal totalDoacao, ItemCestaBasica__c itemCestaBasica) 
    {
        for (ItemEstoque__c itemEstoque : records)
        {
            if (totalDoacao == 0)
            {
                break;
            }
            else
            {
                if (itemCestaBasica.Item__c.equals(itemEstoque.Produto__c))
                {
                    if (itemEstoque.Quantidade__c > 0)
                    {
                        if (totalDoacao <= itemEstoque.Quantidade__c)
                        {
                            item.Quantidade__c += totalDoacao;
                            itemEstoque.Quantidade__c -= totalDoacao;
                            totalDoacao -= totalDoacao;
                        }
                        else
                        {
                            item.Quantidade__c += itemEstoque.Quantidade__c;
                            totalDoacao -= itemEstoque.Quantidade__c;
                            itemEstoque.Quantidade__c = 0;                        
                        }                    
                    }
                }
            }
        }  
    }

}