dev-capec/force-app/main/default/objects/ItemCestaBasica__c/ItemCestaBasica__c.object-meta.xml
<CustomObject>
    <label>Item da Cesta Básica</label>
    <nameField>
        <displayFormat>ICB-{000000}</displayFormat>
        <label>Item da Cesta Básica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens das Cestas Básicas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dev-capec/force-app/main/default/objects/ItemCestaBasica__c/fields/CestaBasica__c.field-meta.xml
<CustomField>
    <fullName>CestaBasica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cesta Básica</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cesta Básica</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens</relationshipLabel>
    <relationshipName>Itens2</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemCestaBasica__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Padrão</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens</relationshipLabel>
    <relationshipName>Itens</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/objects/Product2/recordTypes/CestaBasica.recordType-meta.xml
<RecordType>
    <fullName>CestaBasica</fullName>
    <active>true</active>
    <label>Cesta Básica</label>
</RecordType>

dev-capec/force-app/main/default/classes/ProductsSelector.cls
public without sharing class ProductsSelector 
{
    private static ProductsSelector instance = null;
    public List<Product2> productsCestaBasica {get; private set;}

    private ProductsSelector(){}

    public static ProductsSelector getInstance()
    {
        if (instance == null)
        {
            instance = new ProductsSelector();
        }

        return instance;
    }

    public List<Product2> selectByCestaBasicaId(Set<Id> ids)
    {
        if (productsCestaBasica == null)
        {
            productsCestaBasica = [
                SELECT Id, (SELECT Id, Item__r.Name, Quantidade__c FROM Itens2__r)
                FROM Product2
                WHERE Id IN :ids
                AND RecordTypeId = :Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName().get('CestaBasica').getRecordTypeId()
            ];
        }

        return productsCestaBasica;
    }
}