dev-capec/force-app/main/default/objects/CestaBasica__c/CestaBasica__c.object-meta.xml
<CustomObject>
    <label>Cesta básica</label>
    <nameField>
        <displayFormat>CB-{000000}</displayFormat>
        <label>Cesta básica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cestas básicas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dev-capec/force-app/main/default/objects/ItemCestaBasica__c/ItemCestaBasica__c.object-meta.xml
<CustomObject>
    <label>Item da Cesta Básica</label>
    <nameField>
        <displayFormat>ICB-{000000}</displayFormat>
        <label>Item da Cesta Básica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens das Cestas Básicas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dev-capec/force-app/main/default/objects/ItemCestaBasica__c/fields/CestaBasica__c.field-meta.xml
<CustomField>
    <fullName>CestaBasica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cesta Básica</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cesta Básica</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens</relationshipLabel>
    <relationshipName>Itens2</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemCestaBasica__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Padrão</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens</relationshipLabel>
    <relationshipName>Itens</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/classes/ItensCestasBasicasSelector.cls
public without sharing class ItensCestasBasicasSelector 
{
    private static ItensCestasBasicasSelector instance = null;
    public List<ItemCestaBasica__c> itensCestasBasicas {get; private set;}

    private ItensCestasBasicasSelector(){}

    public static ItensCestasBasicasSelector getInstance()
    {
        if (instance == null)
        {
            instance = new ItensCestasBasicasSelector();
        }

        return instance;
    }

    public List<ItemCestaBasica__c> selectByCestaBasicaId(Set<Id> ids)
    {
        if (itensCestasBasicas == null)
        {
            itensCestasBasicas = [
                SELECT Id, Item__c
                FROM ItemCestaBasica__c
                WHERE CestaBasica__c IN :ids
            ];
        }

        return itensCestasBasicas;
    }
}