dev-capec/force-app/main/default/objects/Doacao__c/Doacao__c.object-meta.xml
<CustomObject>
    <label>Doação</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Doação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Doações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dev-capec/force-app/main/default/objects/ItemDoacao__c/ItemDoacao__c.object-meta.xml
<CustomObject>
    <label>Item de Doação</label>
    <nameField>
        <displayFormat>ID-{000000}</displayFormat>
        <label>Item de Doação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de Doações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dev-capec/force-app/main/default/objects/ItemDoacao__c/fields/Doacao__c.field-meta.xml
<CustomField>
    <fullName>Doacao__c</fullName>
    <label>Doação</label>
    <referenceTo>Doacao__c</referenceTo>
    <relationshipLabel>Itens</relationshipLabel>
    <relationshipName>ItensDoacoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemDoacao__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens de Doações</relationshipLabel>
    <relationshipName>ItensDoacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemDoacao__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

dev-capec/force-app/main/default/classes/ItensDoacoesSelector.cls
public without sharing class ItensDoacoesSelector 
{

    private static ItensDoacoesSelector instance = null;
    public List<ItemDoacao__c> itens {get; private set;}

    private ItensDoacoesSelector(){}

    public static ItensDoacoesSelector getInstance()
    {
        if (instance == null)
        {
            instance = new ItensDoacoesSelector();
        }

        return instance;
    }

    public List<ItemDoacao__c> selectByDoacaoId(Set<Id> ids)
    {
        if (itens == null)
        {
            itens = [SELECT Id, Produto__c, Quantidade__c FROM ItemDoacao__c WHERE Doacao__c IN :ids];
        }

        return itens;
    }

    public List<ItemDoacao__c> selectById(Set<Id> ids)
    {
        if (itens == null)
        {
            itens = [SELECT Id, Produto__c, Quantidade__c FROM ItemDoacao__c WHERE Id IN :ids];
        }

        return itens;
    }

    
}