dev-capec/force-app/main/default/objects/Doacao__c/Doacao__c.object-meta.xml
<CustomObject>
    <label>Doação</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Doação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Doações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dev-capec/force-app/main/default/objects/ItemCestaBasica__c/ItemCestaBasica__c.object-meta.xml
<CustomObject>
    <label>Item da Cesta Básica</label>
    <nameField>
        <displayFormat>ICB-{000000}</displayFormat>
        <label>Item da Cesta Básica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens das Cestas Básicas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dev-capec/force-app/main/default/objects/ItemCestaBasica__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens das Cestas Básicas</relationshipLabel>
    <relationshipName>Itens</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemDoacao__c/ItemDoacao__c.object-meta.xml
<CustomObject>
    <label>Item de Doação</label>
    <nameField>
        <displayFormat>ID-{000000}</displayFormat>
        <label>Item de Doação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de Doações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dev-capec/force-app/main/default/objects/ItemDoacao__c/fields/Doacao__c.field-meta.xml
<CustomField>
    <fullName>Doacao__c</fullName>
    <label>Doação</label>
    <referenceTo>Doacao__c</referenceTo>
    <relationshipLabel>Itens</relationshipLabel>
    <relationshipName>ItensDoacoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemDoacao__c/fields/ItemCestaBasica__c.field-meta.xml
<CustomField>
    <fullName>ItemCestaBasica__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Item da Cesta Básica</label>
    <type>Checkbox</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemDoacao__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens de Doações</relationshipLabel>
    <relationshipName>ItensDoacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemDoacao__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemDoacao__c/recordTypes/CestaBasica.recordType-meta.xml
<RecordType>
    <fullName>CestaBasica</fullName>
    <active>true</active>
    <label>Cesta básica</label>
</RecordType>

dev-capec/force-app/main/default/objects/Product2/recordTypes/CestaBasica.recordType-meta.xml
<RecordType>
    <fullName>CestaBasica</fullName>
    <active>true</active>
    <label>Cesta Básica</label>
</RecordType>

dev-capec/force-app/main/default/classes/ItensDoacoes.cls
public with sharing class ItensDoacoes implements IItensDoacoes
{

    List<ItemDoacao__c> records;
    Map<Id, ItemDoacao__c> mapRecords;

    public ItensDoacoes(List<ItemDoacao__c> records) 
    {
        this.records = records;
    }

    public static ItensDoacoes newInstance(List<ItemDoacao__c> records)
    {
        return new ItensDoacoes(records);
    }

    public ItensDoacoes(Map<Id, ItemDoacao__c> mapRecords) 
    {
        this.mapRecords = mapRecords;
    }

    public static ItensDoacoes newInstance(Map<Id, ItemDoacao__c> mapRecords)
    {
        return new ItensDoacoes(mapRecords);
    }

    public List<ItemDoacao__c> createByCestaBasica(Set<Id> cestasBasicasIds)
    {
        if (!mapRecords.isEmpty())
        {
            Map<Id, ItemCestaBasica__c> itensCestasBasicas = new Map<Id, ItemCestaBasica__c>(ItensCestasBasicasSelector.getInstance().selectByCestaBasicaId(cestasBasicasIds));
            List<ItemDoacao__c> itens = new List<ItemDoacao__c>();

            for (ItemDoacao__c record : records)
            {
                Product2 produto = itensCestasBasicas.get(record.Produto__c);
                itens.add(createRecord(record, produto));
            }
            return itens;
        }

        return null;
    }

    private ItemDoacao__c createRecord(ItemDoacao__c cestaBasica, Product2 produto)
    {
        if (cestaBasica != null && produto != null)
        {
            ItemDoacao__c item = new ItemDoacao__c();
    
            item.Produto__c = produto.Id;
            item.Quantidade__c = 1;
            item.Doacao__c = cestaBasica.Doacao__c;
    
            return item;
        }

        return null;
    }
}