dev-capec/force-app/main/default/objects/Doacao__c/Doacao__c.object-meta.xml
<CustomObject>
    <label>Doação</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Doação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Doações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dev-capec/force-app/main/default/objects/Doacao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Pedido solicitado</fullName>
                <default>true</default>
                <label>Pedido solicitado</label>
            </value>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Montagem</fullName>
            </value>
            <value>
                <fullName>Liberada</fullName>
            </value>
            <value>
                <fullName>Entregue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dev-capec/force-app/main/default/objects/ItemDoacao__c/ItemDoacao__c.object-meta.xml
<CustomObject>
    <label>Item de Doação</label>
    <nameField>
        <displayFormat>ID-{000000}</displayFormat>
        <label>Item de Doação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de Doações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dev-capec/force-app/main/default/objects/ItemDoacao__c/fields/Doacao__c.field-meta.xml
<CustomField>
    <fullName>Doacao__c</fullName>
    <label>Doação</label>
    <referenceTo>Doacao__c</referenceTo>
    <relationshipLabel>Itens</relationshipLabel>
    <relationshipName>ItensDoacoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemDoacao__c/fields/ItemEstoque__c.field-meta.xml
<CustomField>
    <fullName>ItemEstoque__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item de Estoque</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>O estoque desse item está zerado.</errorMessage>
        <filterItems>
            <field>ItemEstoque__c.Quantidade__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ItemEstoque__c</referenceTo>
    <relationshipLabel>Itens de Doações</relationshipLabel>
    <relationshipName>ItensDoacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemDoacao__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens de Doações</relationshipLabel>
    <relationshipName>ItensDoacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/objects/ItemEstoque__c/ItemEstoque__c.object-meta.xml
<CustomObject>
    <label>Item de Estoque</label>
    <nameField>
        <displayFormat>IE-{000000}</displayFormat>
        <label>Item de Estoque</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de Estoques</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dev-capec/force-app/main/default/objects/ItemEstoque__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens de Estoques</relationshipLabel>
    <relationshipName>ItensEstoques</relationshipName>
    <type>Lookup</type>
</CustomField>

dev-capec/force-app/main/default/classes/DoacoesTriggerHandler.cls
public without sharing class DoacoesTriggerHandler 
{
    public static void handleAfterUpdate(List<Doacao__c> records, Map<Id, Doacao__c> oldRecords)
    {
        Set<Id> ids = new Set<Id>();

        for (Doacao__c record : records)
        {
            if (record.Status__c.equals('Cancelada') && !record.Status__c.equals(oldRecords.get(record.Id)))
            {
                ids.add(record.Id);
            }
        }

        handleAfterUpdateEstoque(ids);
    }

    public static void handleAfterUpdateEstoque(Set<Id> idsDoacoes)
    {
        List<ItemDoacao__c> itensDoacoes = ItensDoacoesSelector.getInstance().selectByDoacaoId(idsDoacoes);
        Set<Id> idsProdutos = new Set<Id>();

        for (ItemDoacao__c item : itensDoacoes)
        {
            idsProdutos.add(item.Produto__c);
        }

        List<ItemEstoque__c> itens = ItensEstoquesSelector.getInstance().selectByProduto(idsProdutos);

        ItensEstoques ies = ItensEstoques.newInstance(itens);
        ies.devolveQuantidade(itensDoacoes);
        update ies.records;
    }
}